project:
  type: website

website:
  title: "Modélisation discrète des solides et fluides"
  sidebar:
    contents:
      - index.qmd
      - equations_de_mouvement.ipynb

format:
  html:
    theme: cosmo
    toc: true

execute:
  freeze: auto
